# Generated by Django 5.2.5 on 2025-08-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_block_remove_room_block_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.floor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=6),
        ),
    ]
